services:
  - type: web
    name: ad-tech-quiz-api
    env: node
    root: backend
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ad-tech-quiz-db
          property: connectionString

databases:
  - name: ad-tech-quiz-db
    databaseName: adtechquiz
    user: adtechuser
    plan: free
