services:
  - type: web
    name: ad-tech-quiz-api
    env: node
    region: oregon
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ad-tech-quiz-db
          property: connectionString
      - key: NODE_ENV
        value: production

databases:
  - name: ad-tech-quiz-db
    databaseName: adtechquiz
    user: adtechuser
    region: oregon
    plan: free
